### ISSUE TITLE
Create ckanext-aircan-connector extension

### ISSUE THREAD

**Issue by mbeilin** [datopian/aircan#39]
When user uploads a file with tabular data to portal (CKAN), we want an Airflow DAG to be triggered so the data is uploaded to Datastore.

## Acceptance 

A new ckan extension exists similar to ckanext-datapusher that does the following (TODO: check behaviour of ckanext-datapusher in some detail):

- [x] Can be configured with list of files to process (i.e. tabular ones) - -- DONE -- [DEFAULT_FORMATS](https://github.com/datopian/ckanext-aircan/blob/master/ckanext/aircan_connector/plugin.py#L12)
- [x] On upload of a new file that matches this file list automatically trigger an import of that file via Airflow DAG into datastore
- [x]  Provide an API for manual triggering of an import of an existing file -- **DONE** -- you can do it as such:
```
curl -X POST \
-H 'Authorization: YOUR_CKAN_API_KEY' \
-d '{"resource_id": "RESOURCE_ID"}' \
http://CKAN_HOST/api/action/datapusher_submit
```
with successful  response:
```
{
    "help": "http://ckan:5000/api/3/action/help_show?name=datapusher_submit",
    "success": true,
    "result": {
        "message": "Created <DagRun ckan_api_load_multiple_steps @ 2020-07-06 07:27:15+00:00: manual__2020-07-06T07:27:15+00:00, externally triggered: True>",
        "execution_date": "2020-07-06T07:27:15+00:00",
        "run_id": "manual__2020-07-06T07:27:15+00:00"
    }
}
```

 ## Tasks

- [x] Stub new ckanext-aircan extension -- **DONE** -- [repo](https://github.com/datopian/ckanext-aircan_connector)
- [x]  Write tests for checking functionality (will need to mock aircan API calls).
  - can port material (if exists) from  [ckanext-datapusher](https://github.com/ckan/ckan/tree/master/ckanext/datapusher) logic. - Resolved [by](https://github.com/datopian/ckanext-aircan/pull/4) for currently implemented functionality.
- [x] Implement `push notification` mechanism to notify the loader (Airflow DAG) to upload data to DataStore, like 
[notify](https://github.com/ckan/ckan/blob/master/ckanext/datapusher/plugin.py#L70) from current version. -- **DONE** -- Implemented in [ckanext-aircan](https://github.com/datopian/ckanext-aircan)

**Comment by rufuspollock** [comment]
@mbeilin this is my tidied version. Comments in quotes with bold

---

> **Good job story. we don't have description as a heading. **

When user uploads a file with tabular data to portal (CKAN), we want an Airflow DAG to be triggered so the data is uploaded to Datastore.

## Acceptance 

**This is not an acceptance criteria as it stands - it does not tell me what would happen. Acceptance criteria are checklists ...**

* [ ] The custom extension for notifying(triggering) the Airflow DAG about the data to be uploaded to DataStore is created and installed in CKAN instance.

> here's my version (see also #1 for some acceptance you could reuse maybe). 

A new ckan extension exists similar to ckanext-datapusher that does the following (TODO: check behaviour of ckanext-datapusher in some detail):

* [ ] Can be configured with list of files to process (i.e. tabular ones)
* [ ] On upload of a new file that matches this file list automatically trigger an import of that file via Airflow DAG into datastore
* [ ] Provide an API for  manual triggering of an import of an existing file

NB: unlike current  datapusher extension no UI integration is currently needed.

 ## Tasks

> pretty good,  made some small tweaks.

- [ ] Stub new ckanext-aircan extension
- [ ]  Write tests for checking functionality (will need to mock aircan API calls).
  - can port material (if exists) from  [ckanext-datapusher](https://github.com/ckan/ckan/tree/master/ckanext/datapusher) logic.
- [ ] Implement `push notification` mechanism to notify the loader (Airflow DAG) to upload data to DataStore, like 
[notify](https://github.com/ckan/ckan/blob/master/ckanext/datapusher/plugin.py#L70) from current version.

**Comment by mbeilin** [comment]
Stub new ckanext-aircan extension -- **DONE** -- [repo](https://github.com/datopian/ckanext-aircan_connector)

**Comment by hannelita** [comment]
Repo https://github.com/datopian/ckanext-aircan has been made public and properly renamed

**Comment by hannelita** [comment]
@mbeilin You said you were working on the tests, correct? Can you update this issue?

**Comment by hannelita** [comment]
https://github.com/datopian/ckanext-aircan/pull/4 and initial commit on this repo fix this issue
